package gui.form.message;

import fpoly.tn.helper.CheckValidation;
import fpoly.tn.helper.MouseEffect;
import java.awt.Color;
import javax.swing.Icon;

public class DialogThongBao extends javax.swing.JDialog {

    // validation
    public enum MessageIcon {
        CHECK,
        WARNING,
        QUESTION
    }

    public enum MessageType {
        THONGBAO,
        XACNHAN
    }

    String message;
    String message2;
    String messageNode;
    String messagePunctuation;
    MessageIcon messageIcon;
    MessageType messageType;

    boolean xacNhan;

    public DialogThongBao(java.awt.Frame parent, String message, String messageNode, String message2, MessageIcon messageIcon, MessageType messageType) {
        super(parent, true);
        initComponents();
        setFormUI();

        this.message = message;
        this.message2 = message2;
        this.messageNode = messageNode;
        this.messageIcon = messageIcon;
        this.messageType = messageType;

        loadThongTin();
    }

    public DialogThongBao(java.awt.Frame parent, String message, MessageType messageType) {
        this(parent, message, "", "", null, messageType);
    }
    public DialogThongBao(java.awt.Frame parent, String message,MessageIcon messageIcon, MessageType messageType) {
        this(parent, message, "", "", messageIcon, messageType);
    }

    public DialogThongBao(java.awt.Frame parent, String message, String messageNode, MessageType messageType) {
        this(parent, message, messageNode, "", null, messageType);
    }
    
    public DialogThongBao(java.awt.Frame parent, String message, String messageNode,MessageIcon messageIcon, MessageType messageType) {
        this(parent, message, messageNode, "", messageIcon, messageType);
    }

    public DialogThongBao(java.awt.Frame parent, String message, String messageNode, String message2, MessageType messageType) {
        this(parent, message, messageNode, message2, null, messageType);
    }

    private void loadThongTin() {

        // format messageNode
        if (!CheckValidation.checkStringTrong(messageNode)) {
            messageNode = String.format("<span style = \"font-weight:bold; color:red;\"> %s</span>", messageNode);
        }

        if (!CheckValidation.checkStringTrong(message2)) {
            message2 = " " + message2;
        }

        Icon icon = null;
        String chamCau;

        if (messageIcon != null) {
            switch (messageIcon) {
                case CHECK:
                    icon = (new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/gui/message/icon/icon_check_30.png")));
                    break;
                case QUESTION:
                    icon = (new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/gui/message/icon/icon_question_30.png")));
                    break;
                case WARNING:
                    icon = (new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/gui/message/icon/icon_warning_30.png")));
                    break;
                default:
                    break;
            }
        }
        if (messageType == null) {
            messageType = MessageType.THONGBAO;
        }
        switch (messageType) {
            case THONGBAO:
                bntKhong.setVisible(false);
                bntCo.setText("Đóng");
                chamCau = "!";
                break;
            case XACNHAN:
                chamCau = "?";
                bntKhong.setVisible(true);
                break;
            default:
                chamCau = ".";
                bntKhong.setVisible(false);
                break;
        }

        lbIcon.setIcon(icon);

        String thongBao = String.format("<html><body style=\"text-align: left;text-justify: inter-word;\">%s%s%s%s</body></html>", message, messageNode, message2, chamCau);
        txtMessage.setText(thongBao);
    }

    private void setFormUI() {
        setBackground(new Color(0, 0, 0, 0));
        setMouseEffect();
        getRootPane().setDefaultButton(bntCo);
    }

    private void setMouseEffect() {

        MouseEffect.MouseMovingForm(panelTuaDe, this);
        MouseEffect.addMouseEffect(bntThoat, Color.white, Color.white, new Color(102, 102, 102), new Color(102, 102, 102));
    }

    private void dongForm(boolean xacNhan) {
        this.xacNhan = xacNhan;
        dispose();
    }

    public boolean getResuiltValue() {
        return xacNhan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sPanel1 = new com.shady.scontrols.SPanel();
        panelTuaDe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntThoat = new javax.swing.JLabel();
        txtMessage = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bntCo = new com.shady.scontrols.SButton();
        bntKhong = new com.shady.scontrols.SButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setModal(true);
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        sPanel1.setBackground(new java.awt.Color(255, 255, 255));
        sPanel1.sets_borderColor(new java.awt.Color(204, 204, 204));
        sPanel1.sets_dropShadow(true);
        sPanel1.sets_shadowOpacity(0.2F);
        sPanel1.sets_shadowSize(10);

        panelTuaDe.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Thông báo");

        bntThoat.setBackground(new java.awt.Color(255, 255, 255));
        bntThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntThoat.setForeground(new java.awt.Color(102, 102, 102));
        bntThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntThoat.setText("X");
        bntThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTuaDeLayout = new javax.swing.GroupLayout(panelTuaDe);
        panelTuaDe.setLayout(panelTuaDeLayout);
        panelTuaDeLayout.setHorizontalGroup(
            panelTuaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTuaDeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTuaDeLayout.setVerticalGroup(
            panelTuaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTuaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtMessage.setBackground(new java.awt.Color(255, 255, 255));
        txtMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtMessage.setText("Nội dung");
        txtMessage.setFocusable(false);
        txtMessage.setOpaque(true);

        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        bntCo.setBackground(new java.awt.Color(243, 242, 242));
        bntCo.setText("Có");
        bntCo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bntCo.sets_Radius(10);
        bntCo.sets_borderColor(new java.awt.Color(153, 153, 153));
        bntCo.sets_hoverBackground(new java.awt.Color(228, 228, 228));
        bntCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCoActionPerformed(evt);
            }
        });
        jPanel1.add(bntCo);

        bntKhong.setBackground(new java.awt.Color(243, 242, 242));
        bntKhong.setText("Không");
        bntKhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bntKhong.sets_Radius(10);
        bntKhong.sets_borderColor(new java.awt.Color(153, 153, 153));
        bntKhong.sets_hoverBackground(new java.awt.Color(228, 228, 228));
        bntKhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntKhongActionPerformed(evt);
            }
        });
        jPanel1.add(bntKhong);

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTuaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(sPanel1Layout.createSequentialGroup()
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addComponent(panelTuaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntThoatMouseClicked
        dongForm(false);
    }//GEN-LAST:event_bntThoatMouseClicked

    private void bntCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCoActionPerformed
        dongForm(true);
    }//GEN-LAST:event_bntCoActionPerformed

    private void bntKhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntKhongActionPerformed
        dongForm(false);
    }//GEN-LAST:event_bntKhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogThongBao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DialogThongBao dialog = new DialogThongBao(new javax.swing.JFrame(), "", "", "", null, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.shady.scontrols.SButton bntCo;
    private com.shady.scontrols.SButton bntKhong;
    private javax.swing.JLabel bntThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JPanel panelTuaDe;
    private com.shady.scontrols.SPanel sPanel1;
    private javax.swing.JLabel txtMessage;
    // End of variables declaration//GEN-END:variables
}
