package gui.tab;

import gui.tab.subtab.nhacungcap.SubTabNhaCungCap;


public class TabQuanLyNhaCungCap extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public TabQuanLyNhaCungCap() {
        initComponents();
        tabbedNhaCungCap.addHeader("danhsachncc", "Danh sách NCC", 150, null);
        
        tabbedNhaCungCap.addTab(new SubTabNhaCungCap(), "danhsachncc");
        tabbedNhaCungCap.setSelectTab("danhsachncc");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedNhaCungCap = new com.shady.scontrols.STabbed();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        tabbedNhaCungCap.setHeaderHeight(40);
        tabbedNhaCungCap.setHeaderInsets(new java.awt.Insets(0, 10, 0, 0));
        tabbedNhaCungCap.setHeaderItemPosition(com.shady.scontrols.STabbed.HeaderAlignment.LEFT);
        tabbedNhaCungCap.setItemBorderSize(3);
        tabbedNhaCungCap.setItemFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabbedNhaCungCap.setItemForeground(new java.awt.Color(102, 102, 102));
        tabbedNhaCungCap.setItemHoverBorderColor(new java.awt.Color(248, 210, 175));
        tabbedNhaCungCap.setItemHoverFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabbedNhaCungCap.setItemHoverForeground(new java.awt.Color(102, 102, 102));
        tabbedNhaCungCap.setItemSelectBorderColor(new java.awt.Color(255, 188, 126));
        tabbedNhaCungCap.setItemSelectFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(tabbedNhaCungCap, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(10, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/icon/khachhang.png"))); // NOI18N
        jLabel1.setText("Quản Lý Nhà Cung Cấp");
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(757, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.shady.scontrols.STabbed tabbedNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
