package gui.form.nhanvien;

import fpoly.tn.dal.DALNhanVien;
import fpoly.tn.helper.CheckValidation;
import fpoly.tn.helper.MouseEffect;
import fpoly.tn.helper.ThongBao;
import gui.form.message.DialogThongBao;
import java.awt.Color;

public class frm_doimatkhau extends javax.swing.JDialog {

    String manv;
    
    public frm_doimatkhau(java.awt.Frame parent, String manv) {
        super(parent, true);
        initComponents();
        
        setFormUI();
         
        this.manv = manv;
    }
    
    private void doiMatKhau(){
        
        if(checkValidation()){
            
            String matKhauMoi = txtMatKhauXacNhan.getTextValue();
            
            if(DALNhanVien.doiMatKhau(manv, matKhauMoi)){
                ThongBao.taoThongBao(null, "Đổi mật khẩu thành công", DialogThongBao.MessageIcon.CHECK);
            }else{
                ThongBao.taoThongBao(null, "Lỗi khi đổi mật khẩu", DialogThongBao.MessageIcon.WARNING);
            }
        }
    }
    
    
    private void setFormUI(){
        setBackground(new Color(0, 0, 0, 0));
        setMouseEffect();
    }
    
    private void setMouseEffect(){
       
        MouseEffect.addMouseEffect(bntThoat, Color.red, new Color(102,102,102), Color.white, Color.white);
        // set form moving panel
        MouseEffect.MouseMovingForm(panelTuade,this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sPanel1 = new com.shady.scontrols.SPanel();
        panelTuade = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bntThoat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLuu = new com.shady.scontrols.SButton();
        sButton3 = new com.shady.scontrols.SButton();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhauCu = new com.shady.scontrols.STextField();
        jLabel13 = new javax.swing.JLabel();
        txtMatKhauMoi = new com.shady.scontrols.STextField();
        jLabel14 = new javax.swing.JLabel();
        txtMatKhauXacNhan = new com.shady.scontrols.STextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sPanel1.setBackground(new java.awt.Color(255, 255, 255));
        sPanel1.sets_drawborder(true);
        sPanel1.sets_dropShadow(true);
        sPanel1.sets_shadowOpacity(0.3F);
        sPanel1.sets_shadowSize(10);

        panelTuade.setBackground(new java.awt.Color(0, 153, 255));
        panelTuade.setForeground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Đổi mật khẩu");

        bntThoat.setBackground(new java.awt.Color(0, 153, 255));
        bntThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bntThoat.setForeground(new java.awt.Color(255, 255, 255));
        bntThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntThoat.setText("x");
        bntThoat.setToolTipText("Thoát");
        bntThoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntThoat.setName(""); // NOI18N
        bntThoat.setOpaque(true);
        bntThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTuadeLayout = new javax.swing.GroupLayout(panelTuade);
        panelTuade.setLayout(panelTuadeLayout);
        panelTuadeLayout.setHorizontalGroup(
            panelTuadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTuadeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelTuadeLayout.setVerticalGroup(
            panelTuadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTuadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnLuu.setBackground(new java.awt.Color(247, 246, 246));
        btnLuu.setText("Xác nhận");
        btnLuu.sets_Cursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.sets_Radius(10);
        btnLuu.sets_borderColor(new java.awt.Color(153, 153, 153));
        btnLuu.sets_hoverBackground(new java.awt.Color(238, 238, 238));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuu);

        sButton3.setBackground(new java.awt.Color(247, 246, 246));
        sButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/icon_delete.png"))); // NOI18N
        sButton3.setText("Thoát");
        sButton3.sets_Cursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sButton3.sets_Radius(10);
        sButton3.sets_borderColor(new java.awt.Color(153, 153, 153));
        sButton3.sets_hoverBackground(new java.awt.Color(238, 238, 238));
        sButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(sButton3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mật khẩu cũ");

        txtMatKhauCu.setForeground(new java.awt.Color(51, 102, 255));
        txtMatKhauCu.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtMatKhauCu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMatKhauCu.sets_errorBackground(new java.awt.Color(255, 204, 204));
        txtMatKhauCu.sets_errorBorder(new java.awt.Color(255, 204, 204));
        txtMatKhauCu.sets_errorIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/iconError.png"))); // NOI18N
        txtMatKhauCu.sets_iconLeft(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/icon_password.png"))); // NOI18N
        txtMatKhauCu.sets_iconLeftPadding(8);
        txtMatKhauCu.sets_maxTextLength(150);
        txtMatKhauCu.sets_placeholder("Mật khẩu ...");
        txtMatKhauCu.sets_radius(5);
        txtMatKhauCu.sets_textType(com.shady.scontrols.STextField.textTypeEnum.PASSWORD);
        txtMatKhauCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauCuActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Mật khẩu mới");

        txtMatKhauMoi.setForeground(new java.awt.Color(51, 102, 255));
        txtMatKhauMoi.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtMatKhauMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMatKhauMoi.sets_errorBackground(new java.awt.Color(255, 204, 204));
        txtMatKhauMoi.sets_errorBorder(new java.awt.Color(255, 204, 204));
        txtMatKhauMoi.sets_errorIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/iconError.png"))); // NOI18N
        txtMatKhauMoi.sets_iconLeft(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/icon_password.png"))); // NOI18N
        txtMatKhauMoi.sets_iconLeftPadding(8);
        txtMatKhauMoi.sets_maxTextLength(150);
        txtMatKhauMoi.sets_placeholder("Mật khẩu mới ...");
        txtMatKhauMoi.sets_radius(5);
        txtMatKhauMoi.sets_textType(com.shady.scontrols.STextField.textTypeEnum.PASSWORD);
        txtMatKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauMoiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Xác nhận mật khẩu mới");

        txtMatKhauXacNhan.setForeground(new java.awt.Color(51, 102, 255));
        txtMatKhauXacNhan.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        txtMatKhauXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMatKhauXacNhan.sets_errorBackground(new java.awt.Color(255, 204, 204));
        txtMatKhauXacNhan.sets_errorBorder(new java.awt.Color(255, 204, 204));
        txtMatKhauXacNhan.sets_errorIcon(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/iconError.png"))); // NOI18N
        txtMatKhauXacNhan.sets_iconLeft(new javax.swing.ImageIcon(getClass().getResource("/fpoly/tn/icon/icon_password.png"))); // NOI18N
        txtMatKhauXacNhan.sets_iconLeftPadding(8);
        txtMatKhauXacNhan.sets_maxTextLength(150);
        txtMatKhauXacNhan.sets_placeholder("Mật khẩu mới ...");
        txtMatKhauXacNhan.sets_radius(5);
        txtMatKhauXacNhan.sets_textType(com.shady.scontrols.STextField.textTypeEnum.PASSWORD);
        txtMatKhauXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sPanel1Layout = new javax.swing.GroupLayout(sPanel1);
        sPanel1.setLayout(sPanel1Layout);
        sPanel1Layout.setHorizontalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatKhauXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelTuade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sPanel1Layout.setVerticalGroup(
            sPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanel1Layout.createSequentialGroup()
                .addComponent(panelTuade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhauXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // tabDanhSachNhanVien.loadSQL();
    }//GEN-LAST:event_formWindowClosing

    private void khungFormMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khungFormMouseDragged

    }//GEN-LAST:event_khungFormMouseDragged

    private void bntThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntThoatMouseClicked

        this.dispose();
    }//GEN-LAST:event_bntThoatMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void sButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton3ActionPerformed
         this.dispose();
    }//GEN-LAST:event_sButton3ActionPerformed

    private void txtMatKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauMoiActionPerformed
       doiMatKhau();
    }//GEN-LAST:event_txtMatKhauMoiActionPerformed

    private void txtMatKhauCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauCuActionPerformed
         doiMatKhau();
    }//GEN-LAST:event_txtMatKhauCuActionPerformed

    private void txtMatKhauXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauXacNhanActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_txtMatKhauXacNhanActionPerformed

    private boolean checkValidation() {
        boolean hopLe = false;
        String thongBao1 = "";
        String thongBao2 = "";
        String thongBao3 = "";
        
        // kiem tra null cua 3 textfiled
        // kiem tra do dai mat khau phu hop
        // kiem tra mat khau cu khop
        // kiem tra mat khau moi khop
        if(CheckValidation.checkStringTrong(txtMatKhauCu.getTextValue()) && CheckValidation.checkStringTrong(txtMatKhauMoi.getTextValue()) 
                && CheckValidation.checkStringTrong(txtMatKhauXacNhan.getTextValue())){
            thongBao2 = "Dữ liệu";
            thongBao3 = " không được để trống";
            txtMatKhauCu.sets_error(!hopLe);
            txtMatKhauMoi.sets_error(!hopLe);
            txtMatKhauXacNhan.sets_error(!hopLe);
        }else if(CheckValidation.checkStringTrong(txtMatKhauCu.getTextValue())){
            thongBao2 = "Mật khẩu cũ";
            thongBao3 = " không được để trống";
            txtMatKhauCu.sets_error(!hopLe);
        }else if(CheckValidation.checkStringTrong(txtMatKhauMoi.getTextValue())){
            thongBao2 = "Mật khẩu mới";
            thongBao3 = " không được để trống";
            txtMatKhauMoi.sets_error(!hopLe);
        }else if(CheckValidation.checkStringTrong(txtMatKhauXacNhan.getTextValue())){
            thongBao2 = "Mật khẩu xác nhận";
            thongBao3 = " không được để trống";
            txtMatKhauXacNhan.sets_error(!hopLe);
        }else if(txtMatKhauCu.getTextValue().equals(txtMatKhauMoi.getTextValue())){
            thongBao2 = "Mật khẩu mới";
            thongBao3 = " không được trùng với mật khẩu cũ";
            txtMatKhauMoi.sets_error(!hopLe);
        }else if(DALNhanVien.matKhauKhop(manv, txtMatKhauCu.getTextValue()) == false){
            thongBao2 = "Nhập sai";
            thongBao3 = " mật khẩu cũ";
            txtMatKhauCu.sets_error(!hopLe);
        }else if(txtMatKhauCu.getTextValue().length() < 6){
            thongBao1 = "Mật khẩu cũ phải có";
            thongBao2 = " 6";
            thongBao3 = " kí tự trở lên";
            txtMatKhauCu.sets_error(!hopLe);
        }else if(txtMatKhauMoi.getTextValue().length() < 6){
            thongBao1 = "Mật khẩu mới phải có";
            thongBao2 = " 6";
            thongBao3 = " kí tự trở lên";
            txtMatKhauMoi.sets_error(!hopLe);
        }else if(txtMatKhauXacNhan.getTextValue().length() < 6){
            thongBao1 = "Mật khẩu xác nhận phải có";
            thongBao2 = " 6";
            thongBao3 = " kí tự trở lên";
            txtMatKhauXacNhan.sets_error(!hopLe);
        }else if(!txtMatKhauXacNhan.getTextValue().equals(txtMatKhauMoi.getTextValue())){
            thongBao2 = "Mật khẩu xác nhận";
            thongBao3 = " không khớp";
            txtMatKhauXacNhan.sets_error(!hopLe);
        }else {
            hopLe = true;
        }
        if (!hopLe) {
           ThongBao.taoThongBao(null, thongBao1,thongBao2,thongBao3,DialogThongBao.MessageIcon.WARNING);
        }
        return hopLe;
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_doimatkhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            frm_doimatkhau dialog = new frm_doimatkhau(new javax.swing.JFrame(), "");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel bntThoat;
    public static com.shady.scontrols.SButton btnLuu;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel panelTuade;
    public static com.shady.scontrols.SButton sButton3;
    public static com.shady.scontrols.SPanel sPanel1;
    public static com.shady.scontrols.STextField txtMatKhauCu;
    public static com.shady.scontrols.STextField txtMatKhauMoi;
    public static com.shady.scontrols.STextField txtMatKhauXacNhan;
    // End of variables declaration//GEN-END:variables
}
